version: '3'
services:
  php:
    container_name: php_latest1
    domainname: php
    hostname: php
    build:
      context: docker/php
    working_dir: "/var/www/app"
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.223.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal
    volumes:
      - "./src:/var/www/app"
      - "./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf"
      - "./docker/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "./docker/php/php.ini:/usr/local/etc/php/php.ini"
    tty: true
  nginx:
    container_name: nginx_latest1
    domainname: nginx
    hostname: nginx
    image: nginx:1.13
    volumes:
      - "./src:/var/www/app"
      - "./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - ${HTTP_PORT}:80
    links:
      - "php"
    networks:
      - internal
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.223.0/28
